config/routes.rb
Rails.application.routes.draw do
  get 'books/new'
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as:'update_book'
  delete 'books/:id' => 'books#destroy', as: 'books_destroy'
  root :to => 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title,presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
  if @book.update(book_params)
    flash[:notice] = "Book was successfully updated."
    redirect_to book_path(@book.id)
  else
    @books = Book.all
    render :edit
  end

  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<div>
  <%= flash[:notice] %>
</div>

<h1>Editing Book<h1>
  <% if @book.errors.any? %>
    <%= @book.errors.count %>error prohibited this book from being saved:
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      　<% end %>
      </ul>
    <% end %>

  <%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

  <div class ="field">
    <label for="book_title">Title</label>
    <%= f.text_field :title %>
    <label for="book_body">Body</label>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit 'Update Book' %>
  </div>
  <% end %>

  <%= link_to "Show",book_path(@book.id), method: :get %>
  <%= link_to "Back",books_path, method: :get %>

app/views/books/index.html.erb
<body>
  <p id="notice"></p>
  <h1>Books</h1>
  <table>
  　  <thead>
        <tr>
          <th>Title</th>
          <th>Body</th>
          <th conspan="3"></th>
        </tr>
  　  </thead>
  　  <% @books.each do |book| %>
  　  <tbody>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
          <td>
            <%= link_to "Show",book_path(book.id), method: :get %>
            <%= link_to "Edit",edit_book_path(book.id), method: :get %>
            <%= link_to "Destroy",books_destroy_path(book.id), method: :delete, "data-confirm" =>"本当に削除しますか?" %>
          </td>
      <% end %>
        </tr>
  　  </tbody>
  </table>

  <div>
    <div>
      <%= flash[:notice] %>
    </div>
  <%#= render 'book', book: @book %>
    <h2>New book</h2>
    <% if @book.errors.any? %>
      <%= @book.errors.count %>error prohibited this book from being saved:
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      　<% end %>
      </ul>
    <% end %>
<!--form_with部分-->
    <%= form_with model: @book,  method: :post do |f| %>
    <div class="field">
      <label for="book_title">Title</label>
      <%= f.text_field :title %>
    </div>

    <div class="field">
     <label for="book_body">Body</label>
      <%= f.text_area :body %>
    </div>

    <div class="action">
      <%= f.submit 'Create Book' %>
    </div>

    <% end %>
  </div>
</body>

app/views/books/show.html.erb
<h2>Title</h2>
<p><%= @book.title %></p>
<h2>Body</h2>
<p><%= @book.body %></p>
<%= link_to "Edit",edit_book_path(@book.id), method: :get %>
|
<%= link_to "Back",books_path, method: :get %>

app/views/homes/top.html.erb
<h1>ようこそ<strong>Bookers</strong>へ！</h1>
<p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<p><a href ="/books">start</a></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>